apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: airflow
  annotations:
    github.com/project-slug: wetestroadie/airflow
spec:
  type: other
  lifecycle: unknown
  owner: wetestroadie/team-a
